apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ template "todo.fullname" . }}-todo
  name: todo-storage-service
  labels:
    todo-app-deployment: todo-storage-service
spec:
  replicas: {{ .Values.replicas.todoStorageService }}
  selector:
      matchLabels:
        todo-app-pod: todo-storage-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        todo-app-pod: todo-storage-service
    spec:
      restartPolicy: Always
      containers:
      - image: {{ .Values.todoImageUser  }}/todo-storage-service:{{ .Values.todoVersion }}
        name: todo-storage-service
        envFrom:
          - configMapRef:
              name: todo-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "134217728"
