apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ template "todo.fullname" . }}-todo
  name: todo-storage-ingestion
  labels:
    todo-app-deployment: todo-storage-ingestion
spec:
  replicas: {{ .Values.replicas.todoStorageIngestion }}
  selector:
      matchLabels:
        todo-app-pod: todo-storage-ingestion
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        todo-app-pod: todo-storage-ingestion
    spec:
      restartPolicy: Always
      initContainers:
      - name: init-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nslookup todo-rabbitmq; do echo waiting for RabbitMQ; sleep 2; done;']
      containers:
      - name: todo-storage-ingestion
        image: {{ .Values.todoImageUser  }}/todo-storage-ingestion:{{ .Values.todoVersion }}
        envFrom:
          - configMapRef:
              name: todo-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: POSTGRES_PASSWORD
        resources:
          limits:
            memory: "134217728"
